const mainColor = {
    _red: '#870202',
    _redOp: 'rgba(247, 0, 0, 0.2)',
    _red2: '#cc3300',
    _green: '#028E00',
    _greenOp: 'rgba(35, 247, 0, 0.2)',
    _blue: '#023887',
    _blue2: '#01B9FF',
    _blue3: '#166ED8',
    _blueOp: 'rgba(0, 158, 247, 0.2)',
    _gray: '#A3A3A3',
    _gray2: '#A1AEB7',
    _grayOp: 'rgba(163, 163, 163, 0.2)',
    _textBlack: '#343434',
    _textGray: '#A3A3A3',
    _black: '#000000',
    _blackOp: '#000000AA',
    _white: '#FFFFFF',
    _youngOrange: '#F79400',
    _oldOrange: '#F77700'
}

export const colors = {
    _red: mainColor._red,
    _red2: mainColor._red2,
    _redOp: mainColor._redOp,
    _green: mainColor._green,
    _greenOp: mainColor._greenOp,
    _blue: mainColor._blue,
    _blue2: mainColor._blue2,
    _blue3: mainColor._blue3,
    _blueOp: mainColor._blueOp,
    _gray: mainColor._gray,
    _gray2: mainColor._gray2,
    _grayOp: mainColor._grayOp,
    _textBlack: mainColor._textBlack,
    _textGray: mainColor._textGray,
    _black: mainColor._black,
    _blackOp: mainColor._blackOp,
    _white: mainColor._white,
    _oldOrange: mainColor._oldOrange,
    _youngOrange: mainColor._youngOrange
}
